{{- range $serviceName, $service := .Values.microservices }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.appName }}-{{ $serviceName }} # Unique name for each microservice
  namespace: {{ $service.namespace }}
  labels:
    app: {{ $.Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $.Values.appName }}
      tier: frontend
      
  template:
    metadata:
      labels:
        app: {{ $.Values.appName }}
        tier: frontend
        
    spec: # Pod spec
      containers:
      - name: mycontainer
        image: {{ $service.image.name }}:{{ $service.image.tag }}
        ports:
        - containerPort: {{ $service.service.port }}
        envFrom:
        - configMapRef:
            name: {{ $service.configMapName }}
        resources:
          requests:
            memory: "16Mi"
            cpu: "50m"    # 500milliCPUs (1/2 CPU)
          limits:
            memory: "128Mi"
            cpu: "100m"
{{- end }}

