{{- range $serviceName, $service := .Values.microservices }}
{{- if $service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}-service
  namespace: {{ $service.namespace }}
  labels:
    app: {{ $.Values.appName }}
spec:
  ports:
  - port: {{ $service.service.port }}
    protocol: TCP
    name: flask
  selector:
    app: {{ $.Values.appName }}
    tier: frontend
    microservice: {{ $serviceName }}
  type: {{ $service.service.type }}
{{- end }}
{{- end }}

