appName: myhelmapp
microservices:
  microA:
    enabled: true
    namespace: app1
    replicaCount: 1
    image:
      name: devopsjourney1/mywebapp
      tag: latest
    service:
      port: 80
      type: ClusterIP
    configMapName: myconfigmapv1.0

  microB:
    enabled: true
    namespace: default
    replicaCount: 1
    image:
      name: devopsjourney1/mywebapp
      tag: latest
    service:
      port: 80
      type: ClusterIP
    configMapName: myconfigmapv2.0

